### ISSUE TITLE
Add allowAudioPlaybackCapture and hasFragileUserData to manifest

### ISSUE THREAD

**Issue by JarlPenguin** [juanmuscaria/blockheads-patch#3]
Add `allowAudioPlaybackCapture` and `hasFragileUserData` to the app's AndroidManifest.xml

`allowAudioPlaybackCapture` allows us to capture the internal audio of the game.

`hasFragileUserData` allows the user to choose whether or not to keep their game data preserved when uninstalling the game.

I could do this with a simple bash script, just not sure how to write it to work with your script.

**Comment by juanmuscaria** [comment]
Could you provide an example bash script so I can try to implement on the current one?

**Comment by JarlPenguin** [comment]
apktool d base.apk
sed -i 's|<application android:debuggable="false"|<application android:debuggable="false" android:allowAudioPlaybackCapture="true" android:hasFragileUserData="true"|g' base/AndroidManifest.xml
apktool b base.apk

**Comment by juanmuscaria** [comment]
Implemented
